### ISSUE TITLE
Add armory

### ISSUE THREAD

**Issue by Kyominii** [Kyominii/Cops_FiveM#12]
pliz, more RP (no longer take weapons when take service)

**Comment by skillfr** [comment]
Yop in vestpolice.lua for next update



				if(GetEntityModel(GetPlayerPed(-1)) == hashSkin) then
					SetPedComponentVariation(GetPlayerPed(-1), 9, 4, 1, 2)  --Gilet pare-balles
					SetPedArmour(GetPlayerPed(-1), 500)
				else
					SetPedComponentVariation(GetPlayerPed(-1), 9, 6, 1, 2)
					SetPedArmour(GetPlayerPed(-1), 500)
				end
			end)
		elseif btn == "Enlevez le gilet pare-balles" then
			Citizen.CreateThread(function()
				SetPedComponentVariation(GetPlayerPed(-1), 9, 0, 1, 2)  --Remove Gilet pare-balles
				SetPedArmour(GetPlayerPed(-1), 0)
			end)

**Comment by Kyominii** [comment]
in progress

**Comment by Kyominii** [comment]
in v1.3
