### ISSUE TITLE
HTTP Request for branch version returning 404 Error

### ISSUE THREAD

**Issue by Braanflakes** [Kyominii/Cops_FiveM#186]
In server\server.lua (line 227), the HTTP request is returning a 404 error and not able to grab the required version which is throwing server errors. Not sure what else this breaks.

[https://raw.githubusercontent.com/FiveM-Scripts/Cops_FiveM/master/police/__resource.lua](url) is what is throwing an error while changing to a different branch, such as 'hotfix' instead of master works properly.

![image](https://user-images.githubusercontent.com/13975366/95655185-262c2c00-0acb-11eb-8545-1e0595a962a7.png)
![image](https://user-images.githubusercontent.com/13975366/95655197-36dca200-0acb-11eb-9aac-67ca1af4af50.png)

**Comment by ghermans** [comment]
Please update your version of cops_fivem, as this issue is already fixed.
