### ISSUE TITLE
Migration to Essentialmode 3.0

### ISSUE THREAD

**Issue by Kyominii** [Kyominii/Cops_FiveM#20]
time to go to a better world I think

**Comment by Kyominii** [comment]
finally, no, kanersps close his thread, reopen, reclose, to instable

**Comment by DayField** [comment]
Essentialmode 3.0 is instable :o ?

**Comment by Kyominii** [comment]
it's not supported by Kanersps anymore

**Comment by Xtrem65** [comment]
Looks like EssentialMode 3.x is back on track... :) (3.1.0 released)

He's updating other mods already :
[Simple Banking](https://forum.fivem.net/t/release-es-simple-banking-port-to-3-1-0/18291)

May i suggest to reopen this issue ?

Thanks (And keep up the good work !)

**Comment by Kyominii** [comment]
I'm waiting for other people who want to upgrade to es3. I'll think about it in some days :)

**Comment by Xtrem65** [comment]
Thanks for reopening.
I have asked some of your dependencies to do so. (I am able to give a hand if needed/wanted)

[jobs upgrade issue](https://github.com/PandaBasketteur/Jobs-System-and-Paycheck/issues/3)
[vdk_inventory upgrade issue](https://github.com/vodkhard/vdk_inventory/issues/5)
[vdk_recolt upgrade issue](https://github.com/vodkhard/vdk_recolt/issues/3)

**Comment by ig0ne** [comment]
I think it's a bad idea because for now their is just one mod who as been translated to couchDB maybe wait and see if everybody follow ES3 or not

**Comment by naxed** [comment]
They won't have a choice, MySQL break the server:
"An early warning was given a bit ago, although this may be frustrating this update is REQUIRED servers break with the old version was the entire sever got 'waited' when a DB request was made. Which could time people out, please see that this was neccesary."

**Comment by fapiche** [comment]
SQL will be directly integrate to fivem so ...

**Comment by samgaze** [comment]
NO

**Comment by DayField** [comment]
just wait for a five m update with the sql integration like altis life
