### ISSUE TITLE
Remove guns into police cars

### ISSUE THREAD

**Issue by ig0ne** [Kyominii/Cops_FiveM#22]
have a criminal armed with a shotgun is not a good idea O_O

**Comment by Valderg** [comment]
I have not tried it yet but there is a native for this. 

`void DISABLE_PLAYER_VEHICLE_REWARDS(Player player);`

I would assume in the police script you could create a playerSpawned function and  something like

```
AddEventHandler("playerSpawned", function()
	if not isCop then
        disablePlayerVehicleRewards(-1);
        end
end)
```

Speculation without testing of course, but it is a start in the right direction should the native work.

**Comment by Kyominii** [comment]
add in 1.3
