### ISSUE TITLE
Check Black money

### ISSUE THREAD

**Issue by skillfr** [Kyominii/Cops_FiveM#28]
Check Black money and Delete the total this /check

Banking black money

`RegisterServerEvent('bank:withdrawAmendeb')
AddEventHandler('bank:withdrawAmendeb', function(amount)
    TriggerEvent('es:getPlayerFromId', source, function(user)
			user:removeDirtyMoney(amount)
		CancelEvent()
    end)
end)`

**Comment by Kyominii** [comment]
atm, no black money script is released so this issue is closed until a balck money is released.
If you want to add a feature like that, feel free to adapt this script to your own black money system
