### ISSUE TITLE
Pull "Nom" from Users-table instead of User_vehicle in Licenseplatecheck

### ISSUE THREAD

**Issue by CarmonDK** [Kyominii/Cops_FiveM#33]
Hi - Don't worry, not an issue, more like a question/request.

For people who already got a User-ID script working, with names and stuff, would it be possible in future updates, to pull the username from the users-table, instead of pulling it from the user_vehicle?

For example: `"Licenseplate 1234567 belongs to SteamName"`
So it is: `"Licenseplate 1234567 belongs to Users.nom"`

Anyways, you're doing a great job with this, been able to run great RP with the script.

**Comment by Kyominii** [comment]
https://github.com/Kyominii/Cops_FiveM/blob/master/police/server.lua#L124

It's already working with a "Nom" field in user table

**Comment by CarmonDK** [comment]
I'm a retard, because mine says * in the "Nom" field.... - NO WORRIES!
