### ISSUE TITLE
unable to cuff whitelisted and off-duty cops

### ISSUE THREAD

**Issue by JakeRyan1** [Kyominii/Cops_FiveM#39]
In RP, if you have to cuff a policeman, he shouldn't stay a cop. like a whitelisted cop that is playing as a civilian can be cuffed. Because of right now we cannot cuff another whitelisted policeman.

**Comment by Valderg** [comment]
This is quite simple, i have done it myself on my servers. Remove the check for IsCop in the cuffing script and add the other requests to the IsCop request in citizen.createthread of your client.lua
`if (isInService == false) then
			if (handCuffed == true) then
			  RequestAnimDict('mp_arresting')

			  while not HasAnimDictLoaded('mp_arresting') do
				Citizen.Wait(0)
			  end

			  local myPed = PlayerPedId(-1)
			  local animation = 'idle'
			  local flags = 16

			  TaskPlayAnim(myPed, 'mp_arresting', animation, 8.0, -8, -1, flags, 0, 0, 0, 0)
			end
			
			--Piece of code from Drag command (by Frazzle, Valk, Michael_Sanelli, NYKILLA1127 : https://forum.fivem.net/t/release-drag-command/22174)
			if drag then
				local ped = GetPlayerPed(GetPlayerFromServerId(officerDrag))
				local myped = GetPlayerPed(-1)
				AttachEntityToEntity(myped, ped, 4103, 11816, 0.68, 0.00, 0.0, 0.0, 0.0, 0.0, false, false, false, false, 2, true)
			else
				DetachEntity(GetPlayerPed(-1), true, false)		
			end
			end`

**Comment by Kyominii** [comment]
fix in 1.3
