### ISSUE TITLE
Police Blip Detection

### ISSUE THREAD

**Issue by Valderg** [Kyominii/Cops_FiveM#40]
The first person on duty out of X players will not update to see other on duty officers. Only the people after that first person goes on duty can see him. If the first officer goes off duty, he is lost to the other people on duty, when he re-enters duty he can see the other players but the previous on duty players dont update to see the first persons blip again.

**Comment by Kyominii** [comment]
in progress

**Comment by Kyominii** [comment]
Can you share to me your police's config and have you modify the script ?

**Comment by weiseang0855** [comment]
having same issue

**Comment by Sojobo** [comment]
Also having this issue

**Comment by Valderg** [comment]
Sorry it took so long to respond, i have 1200 people im trying to satisfy haha. So looking into it, the blips dont actually refresh when the inService field is populated again, so i would say possibly request the blips be loaded again every 15,000 ms or even 30,000 to check for new people on service. 

Settings are listed below, as of right now the script is modified, when i originally produced this error it was completely vanilla.

```
useModifiedEmergency = false
useModifiedBanking = true
useVDKInventory = false
useGcIdentity = false
enableOutfits = false
useJobSystem = false
useWeashop = true
useCopWhitelist = true
enableCheckPlate = false
enableOtherCopsBlips = true
useNativePoliceGarage = true
enableNeverWanted = true
```

**Comment by Kyominii** [comment]
Still an issue with 1.4 ?

**Comment by JaxsenL** [comment]
Ill check it out

**Comment by JaxsenL** [comment]
This issue is Fixed
