### ISSUE TITLE
Maybe a option to select MP skin OR Model?

### ISSUE THREAD

**Issue by TheBritishBrotherhood** [Kyominii/Cops_FiveM#47]
The new system is GREAT! 

But is it possibly use noobs who use skin_customisation to have a option in the menu to select police models and skins?

I hope this make sense

**Comment by Kyominii** [comment]
You can already do this : disable enableOutfits

**Comment by Kyominii** [comment]
i think I just understand what you're trying to say, you want to be able to select the skin you want if this parameter is disable, isn't it ?

**Comment by Kyominii** [comment]
https://github.com/Kyominii/Cops_FiveM/issues/36

**Comment by TheBritishBrotherhood** [comment]
Yeah pretty much :) so if you have skins on, you can either select skin options, OR options to select a model
