### ISSUE TITLE
When using essentials 2.0 i cannot see the white list blimp for police

### ISSUE THREAD

**Issue by JakeRyan1** [Kyominii/Cops_FiveM#51]
I cannot see the blue blimp in the service room I am using essentials 2.0 and job system

**Comment by Kyominii** [comment]
I'm using essential 2.0 and I can see it.
You have probably failed the installation

**Comment by JakeRyan1** [comment]
I don't know what i have failed i have installed it 3 times + using it with couch db

**Comment by Kyominii** [comment]
How can you use es2 with couchdb ...

**Comment by JakeRyan1** [comment]
No no no i have another server that uses couchdb fully i have this one that uses mysql async

**Comment by Kyominii** [comment]
And both of them doesn't work ?

**Comment by JakeRyan1** [comment]
No i had couchdb working but i wanted to go fully async and i cannot because i need to have the police script whitelisted

**Comment by Kyominii** [comment]
i haven't any time atm but try to send me your script version
it's a weird issue

**Comment by JakeRyan1** [comment]
I use the latest one that was posted by you
