### ISSUE TITLE
Can't choose aby option

### ISSUE THREAD

**Issue by XIIIG** [Kyominii/Cops_FiveM#58]
Hey,

I don't if that's only me, but I can't choose any option from any menu - police, garages cloakroom etc. Enter button just doesn't work. It worked fine in the previous version.

I'm using legacy version with with mysql-async.

**Comment by Kyominii** [comment]
Have you rename police-legacy to police ?

**Comment by XIIIG** [comment]
ohhh, I forgot abut that while updating.. It works fine now, thanks!
