### ISSUE TITLE
Editing question

### ISSUE THREAD

**Issue by GlimtechArms** [Kyominii/Cops_FiveM#65]
(If there is an answer to this question I can't seem to find it... Is there a way to set a hotkey to go on duty as a leo without going to a station??? If you die and revive, it knocks you off duty and didn't want to have to go back to a station every time... Thanks...)

I received your response and No we are not running Emergency mod and I am unsure where to edit the script for the hot key. Kinda new at this but learning fast... Thanks in advance..

**Comment by Kyominii** [comment]
For the
