### ISSUE TITLE
Saving Issue

### ISSUE THREAD

**Issue by Kyle47650** [Kyominii/Cops_FiveM#67]
When I add a cop to the database and that person leaves and joins back the blue circles at the police stations are no longer there for that person.  FYI, the user data is being uploaded to the MySQL database.

**Comment by Kyominii** [comment]
Which version are you using ?
Please send a console log when police is launching and when a player is connecting

**Comment by Kyle47650** [comment]
I am using the latest version and it does not say any errors about the resource police.  I am now having another problem where anyone can go on duty and the copadd command does not work anymore.  If you could private message me to discuss these problems I would very much appreciate it.

**Comment by Kyle47650** [comment]
Also is this dependent on essential mode?

**Comment by Kyle47650** [comment]
Because I use couchDB for latest essential mode and MySQL for Async and your script

**Comment by Kyle47650** [comment]
I am using latest version (FXServer) and in the console it says started resource police and when someone connecting it says Connecting:(The Player)

**Comment by Kyle47650** [comment]
Could it be that my MySQL database is only writing and not reading?

**Comment by Kyominii** [comment]
Can I have the screenshot ? Because I can't see if there's is any error.
And no one has reporte this issue so you probably failed the installation.
Let's see where ^^

**Comment by Kyle47650** [comment]
Can we team viewer it would make things a lot more easier?

**Comment by GlimtechArms** [comment]
Are you using the Hands Up and Handcuff add-on’s??? Since I installed those mods mine doesn’t work either, there is a conflict there somewhere but no one can seem to find where…

**Comment by Kyle47650** [comment]
add me on discord - Avg_Player#7510

**Comment by Kyle47650** [comment]
BTW there are no errors Kyominii

**Comment by Kyle47650** [comment]
When the player does copadd (the id) it says the message, show the blue circles, and uploads the user data to the MySQL database but when the player leaves and joins back he is not a cop anymore.

**Comment by Kyle47650** [comment]
![capture](https://user-images.githubusercontent.com/30645614/28907870-68c447aa-77ee-11e7-853e-fc0d0f5f989e.PNG)

**Comment by ImDylan93** [comment]
Having the same issue

**Comment by Kyominii** [comment]
It seems to be async yes
Add this in your server.cfg : set mysql_debug true
It enable logs

**Comment by JaxsenL** [comment]
Did you find out the solution to this issue? I have had the same thing for a while now and have even tried reinstalling old versions of async that I know had been working with it before. I have tried using "set mysql_debug true" but no issues have been shown.

**Comment by Kyominii** [comment]
I haven't find solution at this problem.
It's working with some ppl, and not working with others.
I still search why ...

**Comment by Kyominii** [comment]
It's maybe from MySQL-Async, there's a bug in last version (on Linux), try to downgrade MySQL-Async and retry

**Comment by ImDylan93** [comment]
This issues also occurs with couchdb but isn't as often. any ideas? Running the server on the same machine as the CFX server ran on which didn't have this problem. it has only been since FX released.

**Comment by Kyominii** [comment]
still open with 1.4 ?

**Comment by JaxsenL** [comment]
I am still having this same issue.

**Comment by ImDylan93** [comment]
I am unable to test due to being unwilling to add a reletively untested version on our released server. If I find time to setup a private test server, I will.

**Comment by JaxsenL** [comment]
I just named the sql file wrong. it is all working smoothly for me now on mysql

**Comment by JaxsenL** [comment]
Fully working 1.4
