### ISSUE TITLE
Parachute Not Working

### ISSUE THREAD

**Issue by JaxsenL** [Kyominii/Cops_FiveM#68]
When Using the Cops FiveM V1.3.0 resource the built in parachute function does not work. (Basically this resource makes using parachutes impossible.)

This only happens when the Cops FiveM resource is in my server. Even if its the only resource running (Apart from the required/default resources)

https://gyazo.com/a26c8ab874ef243fc12d109db544c84c

**Comment by Kyominii** [comment]
should be fixed, please test and notice me

**Comment by Kyominii** [comment]
https://forum.fivem.net/t/release-cops-fivem-pre-v1-4-0-09-11-2017/17460/1571?u=kyominii
Fixed !
