### ISSUE TITLE
Disconnected player stuck to cop

### ISSUE THREAD

**Issue by ImDylan93** [Kyominii/Cops_FiveM#70]
When a player disconnects while being dragged by a cop, their AI character will remain stuck to that cop for whatever reason.

**Comment by JaxsenL** [comment]
This occurs to me as well however the AI disappears after a few seconds for me. I would say this is not really a problem.

**Comment by Kyominii** [comment]
yeah but it still a bug ^^
If you have a AI stick to you, you can't remove it atm with buttons

**Comment by Kyominii** [comment]
should be fixed, please test and notice me

**Comment by JaxsenL** [comment]
FIXED in 1.4.
