### ISSUE TITLE
No Chat

### ISSUE THREAD

**Issue by JaxsenL** [Kyominii/Cops_FiveM#73]
setting "displayRankBeforeNameOnChat = false," causes chat to not display

**Comment by Kyominii** [comment]
should be fixed, please test and notice me

**Comment by JaxsenL** [comment]
Resolved

**Comment by Kyominii** [comment]
https://forum.fivem.net/t/release-cops-fivem-pre-v1-4-0-09-11-2017/17460/1575?u=kyominii
Fixed.
