### ISSUE TITLE
[Bug] Put Player In Vehicle

### ISSUE THREAD

**Issue by JaxsenL** [Kyominii/Cops_FiveM#74]
This is no longer working in 1.4

**Comment by JaxsenL** [comment]
A temporary fix for this is taking the server.lua from 1.4 and using it with 1.3 that will also allow mysql to work and will have to be used. This is only a temporary solution for players that want to know. (I have been using this with no new issues.)

**Comment by JaxsenL** [comment]
The error code in console that goes with this is as follows...

Error running system event handling function for resource police: citizen:/scripting/lua/scheduler.lua:39: Failed to execute thread: server/server.lua:195: attempt to concatenate a nil value (field 'force_player_get_in_vehicle_part_2')
stack traceback:
     server/server.lua:195: in upvalue 'handler'
     citizen:/scripting/lua/scheduler.lua:124: in function <citizen:/scripting/lua/scheduler.lua:123>
stack traceback:
     [C]: in function 'error'
     citizen:/scripting/lua/scheduler.lua:39: in field 'CreateThreadNow'
     citizen:/scripting/lua/scheduler.lua:123: in function <citizen:/scripting/lua/scheduler.lua:92>

**Comment by Kyominii** [comment]
should be fixed, please test and notice me

**Comment by JaxsenL** [comment]
Testing. I think some new issues might have show up now. I will report

**Comment by JaxsenL** [comment]
Everything seems to be working well!
