### ISSUE TITLE
Fresh FiveM install - only Cops_FiveM mode and getting error

### ISSUE THREAD

**Issue by Codytch** [Kyominii/Cops_FiveM#95]
Hello Kyominni!

I installed my own server and your mod following the instructions. I keep getting this after typing "/copadd (my ID)"

`[    546578] Error running system event handling function for resource police: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/server.lua:60: attempt to index a nil value (global 'MySQL')
[    546594] stack traceback:
[    546610] 	server/server.lua:60: in upvalue 'handler'
[    546610] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[    546610] stack traceback:
[    546625] 	[C]: in function 'error'
[    546625] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[    546641] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>
[    550453] Error running system event handling function for resource police: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/server.lua:240: attempt to index a nil value (global 'MySQL')
[    550453] stack traceback:
[    550469] 	server/server.lua:240: in upvalue 'handler'
[    550469] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[    550485] stack traceback:
[    550500] 	[C]: in function 'error'
[    550500] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[    550516] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>`

Can you help me please?

**Comment by Kyominii** [comment]
attempt to index a nil value (global 'MySQL') => install mysql-async

**Comment by Codytch** [comment]
Thank you very much mate! It works!
